# Default experiment settings
device: auto           # 'auto' | 'cpu' | 'cuda'
dtype: float32         # float32 | bfloat16 | float16
iters: 1000
repeats: 5
classes: 50
seed: 42
fractions: [0.002, 0.004, 0.006, 0.008, 0.01]   # defaults (e.g., Amazon small)
out_dir: outputs
timeout_s: 1800        # per-run timeout budget (baseline guard)
